import { api, displayValue, errorMessage } from "@/lib/api";
import type { AnalyticsOverview, EventSummary } from "@/lib/types";
import { Panel, Timeline } from "@/components/soc-charts";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const query = new URLSearchParams();
  for (const key of ["honeypot", "source_ip", "protocol", "category", "action", "outcome", "minutes", "size"]) if (params[key]) query.set(key, params[key]!);
  const minutes = Number(params.minutes || 60); let data: EventSummary[] = []; let analytics: AnalyticsOverview | null = null; let error = "";
  try { [data, analytics] = await Promise.all([api<EventSummary[]>(`/events?${query}`), api<AnalyticsOverview>(`/analytics/overview?minutes=${[15,60,360,1440,10080].includes(minutes) ? minutes : 60}`)]); } catch (caught) { error = errorMessage(caught, "Unable to load event telemetry"); }
  return <><header className="page-header"><p className="eyebrow">Investigation</p><h2>LIVE EVENTS</h2><p className="lede">Filtered raw telemetry. Expand a row to inspect normalized structured fields.</p></header>
    <form className="filters"><select name="minutes" defaultValue={params.minutes || "60"}><option value="15">15 minutes</option><option value="60">1 hour</option><option value="360">6 hours</option><option value="1440">24 hours</option><option value="10080">7 days</option></select><input name="source_ip" defaultValue={params.source_ip} placeholder="Source IP"/><input name="honeypot" defaultValue={params.honeypot} placeholder="Honeypot ID"/><input name="protocol" defaultValue={params.protocol} placeholder="Protocol"/><input name="category" defaultValue={params.category} placeholder="Category"/><input name="action" defaultValue={params.action} placeholder="Action"/><input name="outcome" defaultValue={params.outcome} placeholder="Outcome"/><select name="size" defaultValue={params.size || "100"}><option value="50">50 results</option><option value="100">100 results</option><option value="200">200 results</option></select><button>APPLY FILTERS</button></form>
    {error ? <p className="error">{error}</p> : <><Panel title="EVENTS OVER TIME"><Timeline data={analytics?.events_over_time || []}/></Panel><div className="event-investigation"><div className="row head"><span>TIME</span><span>SOURCE</span><span>HONEYPOT</span><span>PROTOCOL</span><span>ACTION / OUTCOME</span></div>{data.length ? data.map((item,index)=><details key={item._id || index}><summary className="row"><span>{displayValue(item["@timestamp"])}</span><span>{displayValue(item.source?.ip)}</span><span>{displayValue(item.honeypot?.id)}</span><span>{displayValue(item.network?.protocol)}</span><span>{displayValue(item.event?.action)} / {displayValue(item.event?.outcome)}</span></summary><pre>{JSON.stringify(item,null,2)}</pre></details>) : <div className="chart-empty">NO DATA IN SELECTED TIME RANGE</div>}</div></>}
  </>;
}
