input { beats { port => 5044 } }
filter {
  mutate { add_field => { "[@metadata][trapsig_original]" => "%{message}" } }
  json { source => "message" target => "raw" tag_on_failure => ["_trapsig_parse_failure"] }
  if ![raw][timestamp] and ![raw][@timestamp] { mutate { add_tag => ["_trapsig_parse_failure"] } }
}
