filter {
  if [fields][honeypot_type] == "ssh_telnet" and "_trapsig_parse_failure" not in [tags] {
    mutate { add_field => {
      "[event][id]" => "%{[raw][eventid]}-%{[raw][session]}-%{[raw][timestamp]}"
      "[event][type]" => "info"
      "[service][name]" => "cowrie"
      "[honeypot][id]" => "%{[fields][honeypot_id]}"
      "[honeypot][type]" => "ssh_telnet"
      "[observer][type]" => "honeypot_sensor"
      "[trapsig][sensor_id]" => "%{[fields][sensor_id]}"
      "[source][ip]" => "%{[raw][src_ip]}"
      "[source][port]" => "%{[raw][src_port]}"
      "[destination][port]" => "%{[raw][dst_port]}"
      "[destination][ip]" => "%{[fields][sensor_ip]}"
      "[network][transport]" => "tcp"
      "message" => "%{[raw][message]}"
    } }
    if [raw][protocol] { mutate { add_field => { "[network][protocol]" => "%{[raw][protocol]}" } } }
    else if [raw][dst_port] == 2223 { mutate { add_field => { "[network][protocol]" => "telnet" } } }
    else { mutate { add_field => { "[network][protocol]" => "ssh" } } }
    if [raw][eventid] == "cowrie.login.failed" {
      mutate { add_field => { "[event][category]" => "authentication" "[event][action]" => "login_attempt" "[event][outcome]" => "failure" "[authentication][username]" => "%{[raw][username]}" "[authentication][password]" => "%{[raw][password]}" } }
    } else if [raw][eventid] == "cowrie.login.success" {
      mutate { add_field => { "[event][category]" => "authentication" "[event][action]" => "login_attempt" "[event][outcome]" => "success" "[authentication][username]" => "%{[raw][username]}" "[authentication][password]" => "%{[raw][password]}" } }
    } else if [raw][eventid] == "cowrie.command.input" {
      mutate { add_field => { "[event][category]" => "process" "[event][action]" => "command" "[event][outcome]" => "unknown" "[process][command_line]" => "%{[raw][input]}" } }
    } else {
      mutate { add_field => { "[event][category]" => "session" "[event][action]" => "%{[raw][eventid]}" "[event][outcome]" => "unknown" } }
    }
    date { match => ["[raw][timestamp]", "ISO8601"] target => "@timestamp" }
  }
}
